# Generated by Django 3.1.6 on 2021-05-31 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Let',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('appli', models.TextField(choices=[('teacher', 'Teacher'), ('graduate', 'Graduate')], default='none')),
                ('course', models.TextField(max_length=50, null=True)),
                ('style', models.TextField(choices=[('sr', 'Self Review'), ('rc', 'Review Center')], default='none')),
            ],
        ),
        migrations.CreateModel(
            name='Selfreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('subject', models.TextField(choices=[('gened', 'General Education'), ('profed', 'Profession Educaction'), ('ict', 'Information and Communication Technology')], default='none')),
                ('summary', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ronanprod.let')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.DateTimeField(null=True)),
                ('status', models.TextField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='none')),
                ('strength', models.CharField(max_length=50, null=True)),
                ('weakness', models.CharField(max_length=50, null=True)),
                ('suggestion', models.CharField(max_length=50, null=True)),
                ('user', models.ManyToManyField(to='ronanprod.Let')),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, null=True)),
                ('cadd', models.CharField(max_length=50, null=True)),
                ('fee', models.IntegerField(null=True)),
                ('sched', models.DateTimeField(max_length=50, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ronanprod.let')),
            ],
        ),
    ]
