# Generated by Django 3.1.6 on 2021-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='let',
            name='appli',
        ),
        migrations.AddField(
            model_name='let',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
