# Generated by Django 3.1.6 on 2021-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0002_auto_20210531_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='let',
            name='style',
        ),
        migrations.AddField(
            model_name='let',
            name='Birthday',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
