# Generated by Django 3.1.6 on 2021-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0002_auto_20210423_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='passwordrepeat',
            new_name='birthday',
        ),
        migrations.AddField(
            model_name='item',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
