# Generated by Django 3.1.6 on 2021-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0003_auto_20210531_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='let',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
