# Generated by Django 3.1.6 on 2021-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0003_auto_20210423_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
