# Generated by Django 3.1.6 on 2021-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0004_auto_20210424_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='birthday',
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
