# Generated by Django 3.1.6 on 2021-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0005_auto_20210425_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
