# Generated by Django 3.1.6 on 2021-05-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0005_auto_20210531_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='let',
            name='Birthday',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
