# Generated by Django 3.1.6 on 2021-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0007_auto_20210531_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='result',
            name='status',
        ),
        migrations.AddField(
            model_name='result',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
