# Generated by Django 3.1.6 on 2021-05-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0008_auto_20210531_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Feedback',
        ),
    ]
