# Generated by Django 3.1.6 on 2021-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0009_auto_20210531_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='cadd',
            new_name='Address_of_the_Review_Center',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='cname',
            new_name='Name_of_the_Lecturer',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='fee',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='sched',
            new_name='Schedule_of_the_Review',
        ),
        migrations.AddField(
            model_name='center',
            name='Name_of_the_Review_Center',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
