# Generated by Django 3.1.6 on 2021-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0010_auto_20210531_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='Schedule_of_the_Review',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
