# Generated by Django 3.1.6 on 2021-05-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0011_auto_20210531_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_School', models.CharField(max_length=50, null=True)),
                ('Address_of_the_School', models.CharField(max_length=50, null=True)),
                ('Date_of_the_Exam', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ronanprod.let')),
            ],
        ),
    ]
