# Generated by Django 3.1.6 on 2021-05-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0012_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selfreview',
        ),
    ]
