# Generated by Django 3.1.6 on 2021-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0013_delete_selfreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='let',
            name='Gender',
            field=models.CharField(choices=[('gender', 'Male'), ('gender', 'Female')], default='none', max_length=10),
        ),
    ]
