# Generated by Django 3.1.6 on 2021-06-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0014_let_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Let',
            new_name='Participant',
        ),
    ]
