# Generated by Django 3.1.6 on 2021-06-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0015_auto_20210603_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='address',
            new_name='add',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='course',
        ),
    ]
