# Generated by Django 3.1.6 on 2021-06-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0017_auto_20210603_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentdate', models.DateTimeField(null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('session', models.IntegerField(null=True)),
                ('Lecturer', models.CharField(max_length=50, null=True)),
                ('schedule', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=50)),
                ('payment', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ronanprod.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewcentername', models.CharField(max_length=50, null=True)),
                ('reviewcenteradd', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ronanprod.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, null=True)),
                ('examdate', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ronanprod.participant')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
        migrations.DeleteModel(
            name='Center',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
