# Generated by Django 3.1.6 on 2021-06-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0019_auto_20210611_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.CharField(choices=[('sub1', 'Professional Education'), ('sub2', 'General Education'), ('sub3', 'Technology and Livelihood Education')], default='sub1', max_length=50),
        ),
    ]
