# Generated by Django 3.1.6 on 2021-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0020_auto_20210612_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.CharField(choices=[('profed', 'Professional Education'), ('gened', 'General Education'), ('tle', 'Technology and Livelihood Education')], default='sub1', max_length=50),
        ),
    ]
