# Generated by Django 3.1.6 on 2021-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0021_auto_20210612_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='strength',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='weakness',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
