# Generated by Django 3.1.6 on 2021-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0023_auto_20210622_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ses',
            new_name='disc',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='totalCost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='test',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('user', models.ManyToManyField(to='ronanprod.Participant')),
            ],
        ),
    ]
