# Generated by Django 3.1.6 on 2021-06-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0024_auto_20210623_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enrolment',
        ),
    ]
