# Generated by Django 3.1.6 on 2021-06-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0025_auto_20210623_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payments',
        ),
    ]
