# Generated by Django 3.1.6 on 2021-06-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0026_auto_20210623_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
