# Generated by Django 3.1.6 on 2021-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0027_auto_20210623_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='totalCost',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
