# Generated by Django 3.1.6 on 2021-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0028_auto_20210623_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='totalCost',
            field=models.IntegerField(null=True),
        ),
    ]
