# Generated by Django 3.1.6 on 2021-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0029_auto_20210623_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='disc',
            new_name='quantity1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='totalCost',
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
