# Generated by Django 3.1.6 on 2021-06-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0030_auto_20210623_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='strength',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='suggestion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='weakness',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
