# Generated by Django 3.1.6 on 2021-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0031_auto_20210623_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
