# Generated by Django 3.1.6 on 2021-06-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0033_remove_reviewer_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
