# Generated by Django 3.1.6 on 2021-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronanprod', '0034_remove_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ManyToManyField(to='ronanprod.Participant'),
        ),
    ]
